apiVersion: v1
kind: Service
metadata:
  name: blog-fe-service
  labels:
    app: blog-fe-app
spec:
  type: ClusterIP
  selector:
    app: blog-fe-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
